### ISSUE TITLE
Holbæk Kommune hus nummer flere cifre

### ISSUE THREAD

**Issue by knudhamm** [briis/affalddk#306]
### Describe the issue

Hvis der søges på flere husnummere f.eks. Holbæk, 4300, Fyrren og 4-16, så fejler den. Der sker intet.
Hvis der søges på et enkelt husnummer f.eks. Holbæk, 4300, Fyrren og 7, så virker den.

### What version of Home Assistant Core has the issue?

2025.5.2

### What type of installation are you running?

Home Assistant Core

### What version of the integration are you using?

2.5.0-beta-3

### Diagnostics information

-

### Anything in the logs that might be useful for us?

```txt

```

**Comment by TermeHansen** [comment]
Det her er addresserne på vejen fra deres API:

![Image](https://github.com/user-attachments/assets/3858cab3-adf2-404b-8894-8405f057e65b)

**Comment by TermeHansen** [comment]
Der er en masse affaldstyper vi ikke har lige nu, så dem fikser jeg lige så de kommer med i næste release...

**Comment by knudhamm** [comment]
Lyder sørme godt med de typer, der mangler.
Ja, underligt - men det er en etage ejendom, så derfor tallet 2- 16.
Prøvede med kun tallet 2 og her virkede det også - samt 2- 16 er også god
nok.
Men måske dokumentation skal opdateres, da man evt. kan finde på at skrive
= husnummer 8, og så finder den jo ikke noget.
Med mindre du kan kode dig ud af det :-).

Den fre. 23. maj 2025 kl. 21.25 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by knudhamm** [comment]
Det har du nok ret i.

Ja, det kunne jo være smart med den drop down liste.


Den lør. 24. maj 2025 kl. 14.59 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by knudhamm** [comment]
Hej Rasmus,

Det virker. Tak for hjælpen.

[image: image.png]

Den man. 26. maj 2025 kl. 17.23 skrev Rasmus Lundsgaard <
***@***.***>:

**Comment by TermeHansen** [comment]
Jeg ser ikke noget i loggen der indikerer at der er nogle fraktioner vi ikke genkender. Kan du se dem i Fors appen eller online andre steder da?

**Comment by knudhamm** [comment]
På: https://www.fors.dk/affald/afhentning-af-affald/ 
kan jeg søge på adressen og får:

Du har søgt på adressen: Fyrren 2 - 16 (4300 Holbæk)

Næste tømningsdag: Torsdag den 29. maj 2025 (Pap, Metal, Glas, Papir, Plast/MDK)

Hjælper det dig evt. eller har jeg overset noget?

**Comment by TermeHansen** [comment]
via data fra fors app'en får vi disse (se beskrivelsen det er de data vi får som vi prøver at oversætte):
```
========================================================
Farligt affald & Miljøboks:
  Nøgle:  farligtaffaldmiljoboks
  Gruppe:  farligtaffaldmiljoboks
  Navn:  Farligt affald & Miljøboks
  Dato:  14-07-2025
  Beskrivelse:  Miljøskab
  Icon:  mdi:recycle
  Picture:  farligtaffaldmiljoboks.svg
  Sidst Opdateret:  2025-05-27 08:37
  ======================================================
Pap:
  Nøgle:  pap
  Gruppe:  pap
  Navn:  Pap
  Dato:  29-05-2025
  Beskrivelse:  770L Pap 14.dg Stand
  Icon:  mdi:note
  Picture:  pap.svg
  Sidst Opdateret:  2025-05-27 08:37
  ======================================================
Plast & Madkarton:
  Nøgle:  plastmadkarton
  Gruppe:  plastmadkarton
  Navn:  Plast & Madkarton
  Dato:  29-05-2025
  Beskrivelse:  770L PMDK 4. uge Stand
  Icon:  mdi:trash-can
  Picture:  plastmadkarton.svg
  Sidst Opdateret:  2025-05-27 08:37
  ======================================================
Restaffald:
  Nøgle:  restaffald
  Gruppe:  restaffald
  Navn:  Restaffald
  Dato:  02-06-2025
  Beskrivelse:  770L Rest uge Stand
  Icon:  mdi:trash-can
  Picture:  restaffald.svg
  Sidst Opdateret:  2025-05-27 08:37
  ======================================================

```

er det `770L PMDK 4. uge Stand` du tænker der også dækker over metal og glas så? Det kan jeg godt rette det til.
